services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: atr
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - ./mongo-data:/data/db
      - ./scripts/mongodb-init.sh:/init-replica.sh
    command: /init-replica.sh
    restart: always

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always

    # Expose both ports on your host
    ports:
      - "1883:1883" # Raw MQTT
      - "9001:9001" # WebSockets

    # Mount your local config, data, and logs
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongo-data:
    driver: local
  mosquitto:
    driver: local
