### Variables 
@host = http://0.0.0.0:8000
@route = users
@userName = Fulaninho
@userNickname = Fulano
@userEmail = fulano@hotmail.com
@userPassword = 123456
@userPhoneNumber = 71999258225
@userPixType = cpf_cnpj
@userPixValue = 86231101533
@userProfilePhotoPath=./moon-sunset-horizon-1920x1080-15494.jpg

# @name createUser
POST {{host}}/{{route}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="name"

{{userName}}  
--WebKitFormBoundary
Content-Disposition: form-data; name="nickname"

{{userNickname}}
--WebKitFormBoundary
Content-Disposition: form-data; name="email"

{{userEmail}}
--WebKitFormBoundary
Content-Disposition: form-data; name="password"

{{userPassword}}
--WebKitFormBoundary
Content-Disposition: form-data; name="phone_number"

{{userPhoneNumber}}
--WebKitFormBoundary
Content-Disposition: form-data; name="pix_type"

{{userPixType}}
--WebKitFormBoundary
Content-Disposition: form-data; name="pix_value"

{{userPixValue}}
--WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="moon-sunset-horizon-1920x1080-15494.jpg"
Content-Type: application/jpg

< {{userProfilePhotoPath}}
--WebKitFormBoundary--

###

# @name getUsers
GET {{host}}/{{route}}

@userId = {{getUsers.response.body.0.id}}

###

# @name getUserById
GET {{host}}/{{route}}/{{userId}}

###

# @name me
GET {{host}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzA2NDM2fQ.aUHzBgbsJFARJCnFxKvDN0QYgJyE-KL8m96_pmCnNhQ

###
