version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: browser_user
      ME_CONFIG_BASICAUTH_PASSWORD: browser_pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT Port
      - "9001:9001" # WebSocket Port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1884:1883" # MQTT Port for EMQX
      - "18083:18083" # EMQX Dashboard
    environment:
      - EMQX_LOADED_PLUGINS="emqx_auth_username"
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_DEFAULT_USER=admin
      - EMQX_DEFAULT_PASSWORD=public
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
