@environment = dev
@route = crypto-coins
@id_bitcoin = 679599f56ff7a545f3e03729

# @name getCryptoCoins
GET {{baseUrl}}/{{route}} HTTP/1.1

###

# @name getCryptoCoinWithMetrics
GET {{baseUrl}}/{{route}}/{{id_bitcoin}}/prices-metrics HTTP/1.1

###

# @name createCryptoCoin
POST {{baseUrl}}/{{route}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bitcoin",
  "symbol": "BTC",
  "image": {
    "thumb": "https://coin-images.coingecko.com/coins/images/1/thumb/bitcoin.png?1696501400",
    "small": "https://coin-images.coingecko.com/coins/images/1/small/bitcoin.png?1696501400",
    "large": "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400"
  },
  "dataInterval": 5
}

###

# @name updateCryptoCoin
PUT {{baseUrl}}/{{route}}/{{createCryptoCoin.response.body._id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Ethereum"
}


###

# @name deleteCryptoCoin
DELETE {{baseUrl}}/{{route}}/{{createCryptoCoin.response.body._id}} HTTP/1.1
