@environment = dev
@route = monitor

# @name startCollector
POST {{baseUrl}}/{{route}}/start HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzlhZTE4ZjM5YTI4ZDM5YmU4MmQzODYiLCJpYXQiOjE3MzgyOTc4NDksImV4cCI6MTczODM4NDI0OX0.38R9c79SwuzJjZnuSqsxVDeyPmc6lGXytNOk7NP-lPY

###

# @name stopCollector
POST {{baseUrl}}/{{route}}/stop HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzlhZTE4ZjM5YTI4ZDM5YmU4MmQzODYiLCJpYXQiOjE3MzgyOTc4NDksImV4cCI6MTczODM4NDI0OX0.38R9c79SwuzJjZnuSqsxVDeyPmc6lGXytNOk7NP-lPY

